// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(init, update, render, _) {
  var state = [init];
  var dispatch = function (a) {
    var match = Curry._2(update, a, state[0]);
    var eff = match[1];
    state[0] = match[0];
    Curry._2(render, state[0], dispatch);
    setTimeout((function () {
            return Curry._1(eff, dispatch);
          }), 1);
    return /* () */0;
  };
  Curry._2(render, state[0], dispatch);
  return dispatch;
}

exports.make = make;
/* No side effect */
