// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(init, update, render, $staropt$star, $staropt$star$1, $staropt$star$2, _) {
  var onAction = $staropt$star ? $staropt$star[0] : (function () {
        return /* () */0;
      });
  var onUpdate = $staropt$star$1 ? $staropt$star$1[0] : (function () {
        return /* () */0;
      });
  var onLoad = $staropt$star$2 ? $staropt$star$2[0] : (function (_, _$1) {
        return /* () */0;
      });
  var state = [init];
  var dispatch = function (a) {
    Curry._1(onAction, a);
    var match = Curry._2(update, a, state[0]);
    var eff = match[1];
    state[0] = match[0];
    Curry._1(onUpdate, state[0]);
    Curry._2(render, state[0], dispatch);
    setTimeout((function () {
            return Curry._1(eff, dispatch);
          }), 1);
    return /* () */0;
  };
  Curry._2(onLoad, state[0], dispatch);
  Curry._2(render, state[0], dispatch);
  return dispatch;
}

exports.make = make;
/* No side effect */
